# addons (0â€“3): 0 = none, 1 = first addon, 2 = second addon, 3 = both addons.
# mount uses clientid from mounts.toml
# premium = true: restricts this option to premium accounts only.
# showPremiumOption = true: shows the premium option to free accounts but keeps it locked.

[Citizen]
startingLevel = 1
baseHealth = 150
baseMana = 0
baseCapacity = 400
premium = true
showPremiumOption = false
vocation = 0
sex = "male"
towns = [1, 2, 3]
outfit = {id = 128, head = 128, body = 114, legs = 128, feet = 114, addons = 0, mount = 0}
skills = {fist = 10, sword = 21, axe = 10, club = 10, distance = 10, shield = 10, fishing = 10, magiclevel = 0}

[Resident]
startingLevel = 1
baseHealth = 150
baseMana = 0
baseCapacity = 400
premium = false
showPremiumOption = false
vocation = 0
sex = "female"
towns = [1, 2, 3]
outfit = {id = 136, head = 128, body = 114, legs = 128, feet = 114, addons = 0, mount = 0}
skills = {fist = 10, sword = 10, axe = 10, club = 10, distance = 10, shield = 10, fishing = 10, magiclevel = 0}
