# If premium = true and showPremiumOption = false, non-premium accounts won't see this option.
# If premium = true and showPremiumOption = true, it will be shown but blocked for non-premium accounts.

[Citizen]
startingLevel = 1
baseHealth = 150
baseMana = 0
baseCapacity = 400
premium = true
showPremiumOption = false
vocation = 0
sex = "male"
towns = [1, 2, 3]
outfit = {id = 128, head = 1, body = 1, legs = 1, feet = 1, mount = 0}
skills = {fist = 1, sword = 1, axe = 1, club = 1, shield = 1, fishing = 1}

[Resident]
startingLevel = 1
baseHealth = 150
baseMana = 0
baseCapacity = 400
premium = false
showPremiumOption = false
vocation = 0
sex = "female"
towns = [1, 2, 3]
outfit = {id = 136, head = 1, body = 1, legs = 1, feet = 1, mount = 0}
skills = {fist = 1, sword = 1, axe = 1, club = 1, shield = 1, fishing = 1}
